todolist/Userapp/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import * 
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'user_urls'

urlpatterns = [
   
    path('userregistration/',BaseRegisterView.as_view(),name='userregistration'),
    path('userlogin/',UserLoginView.as_view(),name='userlogin'),
    path("index/",views.index),
    path('home/', views.Homepage,name='home'),
    path('contact/', views.contact,name='contact'),
    path("logout/",views.Logout,name="logout"),

    path('add/',AddTask.as_view(),name='add_task'),
    # path('add/',views.AddTask,name='add_task'),

    path('view/',ViewTask.as_view(),name='view_task'),
    # path('view/',views.ViewTask,name='view_task'),

    path('<int:pk>/detail/',DetailTask.as_view(),name='detail_task'),
    path('<int:pk>/delete/',DeleteTask.as_view(),name='delete_task'),
    path('<int:pk>/update/',UpdateTask.as_view(),name='update_task'),
#    path('view/', login_required(ViewTask.as_view(),login_url='/user/userlogin')),
    path('email/',views.sendmail,name='send_mail'),
   path('change-status/<int:id>/<str:status>', change_task ), 


]

todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('Userapp.urls')),
]

todolist/templates/userportal/add_task.html
{% extends 'userportal/base2.html' %}
{% block container %}

		<section class="section-1">
			<h1>WELCOME</h1>
			<p><div class = 'card'>
        <div class='card-header'>
            <h5 class = "class-title">Add New Task</h5>
        </div>
        <div class='card-body'>
            <form method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-success">create</button>
            </form>
        </div>
    </div></p>
		</section>
	</div>

</body>
</html>
{% endblock %}


{% comment %} {% extends 'userportal/base1.html' %}
{% block container %}
<div class = 'card'>
    <div class='card-header'>
        <h5 class = "class-title">Add New Task</h5>
    </div>
    <div class='card-body'>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">create</button>
        </form>
    </div>
</div>
{% endblock %} {% endcomment %}

todolist/templates/userportal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>Todo</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/homepage.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animated.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    
   {% block head %}{% endblock head %}
</head>

<body>

  <!-- ***** Preloader Start ***** -->
  <div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
  <!-- ***** Preloader End ***** -->

  <!-- Pre-header Starts -->
  <div class="pre-header">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-sm-8 col-7">
          <ul class="info">
            <li><a href="#"><i class="fa fa-envelope"></i>contacttodo@gamil.com</a></li>
            {% comment %} <li><a href="#"><i class="fa fa-phone"></i>010-020-0340</a></li> {% endcomment %}
          </ul>
        </div>
        {% comment %} <div class="col-lg-4 col-sm-4 col-5">
          <ul class="social-media">
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-behance"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
          </ul>
        </div> {% endcomment %}
      </div>
    </div>
  </div>
  <!-- Pre-header End -->

  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky wow slideInDown" data-wow-duration="0.75s" data-wow-delay="0s">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="main-nav">
            <!-- ***** Logo Start ***** -->
            <a href="index.html" class="logo">
              <img src="assets/images/logo-v1.png" alt="">
            </a>
            <!-- ***** Logo End ***** -->
            <!-- ***** Menu Start ***** -->
            <ul class="nav">
              <li class="scroll-to-section"><a href="#top" class="active">Home</a></li>
              <li class="scroll-to-section"><a href="">Features</a></li>
              <li class="scroll-to-section"><a href="#about">About Us</a></li>
              <li class="scroll-to-section"><a href="{% url 'user_urls:contact' %}">Contact Us</a></li>
              <li class="scroll-to-section"><a href="{% url 'user_urls:userlogin' %}">Login</a></li> 
              <li class="scroll-to-section"><div class="border-first-button"><a href="{% url 'user_urls:userregistration' %}">Create An Account</a></div></li> 
            </ul>        
            <a class='menu-trigger'>
                <span>Menu</span>
            </a>
            <!-- ***** Menu End ***** -->
          </nav>
        </div>
      </div>
    </div>
  </header>
  {% block custom_css %}{% endblock  %}
   {% block body_block %}{% endblock  %}

  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/js/owl-carousel.js' %}"></script>
  <script src="{% static 'assets/js/animation.js' %}"></script>
  <script src="{% static 'assets/js/imagesloaded.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script>
   
  {% block scripts %} {% endblock %}


</body>

</html> 

todolist/templates/userportal/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block meta_tags %}{% endblock %}
    <title>{% block title %}Add Task{% endblock %}</title>

    {% block css %}
    <link rel = "stylesheet" 
         href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
         integrity = "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
         crossorigin = "anonymous">
    {% endblock %}
    {% block custom_css %}
    {% endblock %}
</head>
<body>
    {% comment %} {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class = "container">
        <a class="navbar-brand" href="#">Django</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="">Add Service Provider  <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="">View Service Provider <span class="sr-only">(current)</span></a>
              </li>
            </ul>
        </div>
      </div>  
    </nav>
    {% endblock %} {% endcomment %}

    <div class = "container mt-4">
    {% block container %}
    {% endblock %}
    </div>

    {% block js %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% endblock %}

    {% block custom_js %}
    {% endblock %}

    
</body>
</html>

todolist/templates/userportal/base2.html
<!DOCTYPE html>
<html>
<head>
	<title>Dashboard</title>
    {% block css %}
    <link rel = "stylesheet" 
         href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
         integrity = "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
         crossorigin = "anonymous">
    {% endblock %}
    {% block custom_css %}
    {% endblock %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="/static/assets/css/sidebar.css">
</head>
<body>
	<input type="checkbox" id="checkbox">
	<header class="header">
		<h2 class="u-name"><a href="{% url 'user_urls:home'  %}">Home</a>
			<label for="checkbox">
				<i id="navbtn" class="fa fa-bars" aria-hidden="true"></i>
			</label>
		</h2>
		<i class="fa fa-user" aria-hidden="true"></i>
	</header>
	<div class="body">
		<nav class="side-bar">
			{% comment %} <div class="user-p">
				<img src="img/user.jpg">
				<h4>Elias</h4>
			</div> {% endcomment %}
			<ul>
				<li>
					<a href="{% url 'user_urls:add_task' %}">
						<i class="fa fa-desktop" aria-hidden="true"></i>
						<span>Add Task</span>
					</a>
				</li>
				<li>
					<a href="{% url 'user_urls:view_task' %}">
						<i class="fa fa-envelope-o" aria-hidden="true"></i>
						<span>View Task</span>
					</a>
				</li>
				<li>
					<a href="#">
						<i class="fa fa-comment-o" aria-hidden="true"></i>
						<span>Comment</span>
					</a>
				</li>
				<li>
					<a href="#">
						<i class="fa fa-info-circle" aria-hidden="true"></i>
						<span>About</span>
					</a>
				</li>
				<li>
					<a href="#">
						<i class="fa fa-cog" aria-hidden="true"></i>
						<span>Setting</span>
					</a>
				</li>
				<li>
					<a href="{% url 'user_urls:userlogin' %}">
						<i class="fa fa-power-off" aria-hidden="true"></i>
						<span>Logout</span>
					</a>
				</li>
			</ul>
		</nav>
        <section class="section-1">
        {% block container %}
        {% endblock %}

todolist/templates/userportal/contactus.html
    <link rel="stylesheet" href="/static/assets/css/contact.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show my-0" role="alert">
      <strong>{{ message }}</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
     {% endfor %}
    {% endif %}
    
        
         
<div class="contact-section">

  <h1>Contact Us</h1>
  <div class="border"></div>
  <form class="contact-form " action="" method="post">
    {% csrf_token %}
    <input type="text" class="contact-form-text" id="name" name="name" placeholder="Your name">
    <input type="email" class="contact-form-text" id="email" name="email" placeholder="Your email">
    <input type="text" class="contact-form-text" id="phone" name="phone" placeholder="Your phone">
    <textarea class="contact-form-text" id="desc" name="desc" placeholder="Your message"></textarea>
    <input type="submit" class="contact-form-btn" value="Send">
  </form>
</div>

todolist/templates/userportal/delete_task.html
{% extends 'userportal/base1.html' %}
{% block container %}
<div class = 'card'>
    <div class='card-header'>
        <h5 class = "class-title">Delete Task{{object.id}}</h5>
    </div>
    <div class='card-body'>
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role='alert'>
                Are you sure you want to delete <strong>{{object}}</strong>
            </div>
            <button type="submit" class="btn btn-success">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

todolist/templates/userportal/detail_task.html
{% extends 'userportal/base1.html' %}
{% block container %}
<div class = 'card'>
    <div class='card-header'>
        <h5 class = "class-title">Task Details #{{task.id}}</h5>
    </div>
    <div class='card-body'>
    <dl class='raw'>
        <dt class='col-sm-3'>Task Name</dt>
        <dd class='col-sm-9'>{{ task.task_name}}</dd>
        
        <dt class='col-sm-3'>Task Description</dt>
        <dd class='col-sm-9'>{{ task.task_description}}</dd>
    </dl>
    </div>
</div>
{% endblock %}

todolist/templates/userportal/homepage.html
{% extends 'userportal/base.html' %} {% load static %} {% block head %}
<title>Todo</title>
{% endblock %} {% block body_block %}
  <!-- ***** Header Area End ***** -->

  <div class="main-banner wow fadeIn" id="top" data-wow-duration="1s" data-wow-delay="0.5s">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
            <div class="col-lg-6 align-self-center">
              <div class="left-content show-up header-text wow fadeInLeft" data-wow-duration="1s" data-wow-delay="1s">
                <div class="row">
                  <div class="col-lg-12">
                    <h6>Project Organizer</h6>
                    <h2>Free up your mental space by managing your task with todo</h2>
                    <p>before todo projects were scattered and things slip, after todo everything is organized and progress is clean.</p>
                  </div>
                  <div class="col-lg-12">
                    <div class="border-first-button scroll-to-section">
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="right-image wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.5s">
                <img src="/static/assets/images/services-image-03.jpg" alt="">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="about" class="about section">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
            <div class="col-lg-6">
              <div class="about-left-image  wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.5s">
                <img src="/static/assets/images/about-dec.png" alt="">
              </div>
            </div>
            <div class="col-lg-6 align-self-center  wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.5s">
              <div class="about-right-content">
                <div class="section-heading">
                  <h6>About Us</h6>
                  <h4>Who is Todo</h4>
                  <div class="line-dec"></div>
                </div>
                <p>From task management to setting up priorities and workflows.We can decrease the amount of time is takes to manage a project.</p>
                {% comment %} <div class="row">
                  <div class="col-lg-4 col-sm-4">
                    <div class="skill-item first-skill-item wow fadeIn" data-wow-duration="1s" data-wow-delay="0s">
                      <div class="progress" data-percentage="90">
                        <span class="progress-left">
                          <span class="progress-bar"></span>
                        </span>
                        <span class="progress-right">
                          <span class="progress-bar"></span>
                        </span>
                        <div class="progress-value">
                          <div>
                            90%<br>
                            <span>Coding</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-sm-4">
                    <div class="skill-item second-skill-item wow fadeIn" data-wow-duration="1s" data-wow-delay="0s">
                      <div class="progress" data-percentage="80">
                        <span class="progress-left">
                          <span class="progress-bar"></span>
                        </span>
                        <span class="progress-right">
                          <span class="progress-bar"></span>
                        </span>
                        <div class="progress-value">
                          <div>
                            80%<br>
                            <span>Photoshop</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-sm-4">
                    <div class="skill-item third-skill-item wow fadeIn" data-wow-duration="1s" data-wow-delay="0s">
                      <div class="progress" data-percentage="80">
                        <span class="progress-left">
                          <span class="progress-bar"></span>
                        </span>
                        <span class="progress-right">
                          <span class="progress-bar"></span>
                        </span>
                        <div class="progress-value">
                          <div>
                            80%<br>
                            <span>Animation</span>
                          </div>
                        </div>
                      </div> {% endcomment %}
                    {% comment %} </div>
                  </div> {% endcomment %}
                </div> 
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  


  {% endblock %} {% block scripts %} {% endblock %}

todolist/templates/userportal/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{request.user}}</h1>
    <form method = 'post' action ="{% url 'user_urls:userlogin' %}">
        {% csrf_token %}
        {{form.as_p}}
        <input type = "submit" value = "logout">
    </form>
</body>
</html>

todolist/templates/userportal/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    
    <!-- ===== Iconscout CSS ===== -->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">

    <!-- ===== CSS ===== -->
    <link rel="stylesheet" href="/static/assets/css/login.css">
         
    <!--<title>Login & Registration Form</title>-->
</head>
<body>
    
    <div class="container">
        <div class="forms">
            <div class="form login">
                <span class="title">Login</span>

                <form action="" method="post">
                  {% csrf_token%}
                    <div class="input-field">
                        {{form.username}}
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        {{form.password}}
                        <i class="uil uil-lock icon"></i>
                        <i class="uil uil-eye-slash showHidePw"></i>
                    </div>

                    <div class="checkbox-text">
                        <div class="checkbox-content">
                            <input type="checkbox" id="logCheck">
                            <label for="logCheck" class="text">Remember me</label>
                        </div>
                        
                        <a href="#" class="text">Forgot password?</a>
                    </div>

                    <div class="input-field button">
                        <input type="submit" value="Login">
                        <button>Login</button>
                    </div>
                </form>

                <div class="login-signup">
                    <span class="text">Not a member?
                        <a href="{% url 'user_urls:userregistration' %}" class="text signup-link">Signup now</a>
                    </span>
                </div>
            </div>

            <!-- Registration Form -->

    <script src="/static/assets/js/signup.js"></script>
	<script>
var form_fields = document.getElementsByTagName('input')
form_fields[1].placeholder='Username';
form_fields[2].placeholder='password';

</script>

</body>
</html>

todolist/templates/userportal/registration.html
<!DOCTYPE html>
<!-- === Coding by CodingLab | www.codinglabweb.com === -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
    <!-- ===== Iconscout CSS ===== -->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">

    <!-- ===== CSS ===== -->
    <link rel="stylesheet" href="/static/assets/css/signup.css">
         
    <!--<title>Login & Registration Form</title>-->
</head>
<body>
    
    <div class="container">
        <div class="forms">
            <div class="form signup">
                <span class="title">Registration</span>

                <form action="" method="post">
                    {% csrf_token %}
                    <div class="input-field">
                        {{form.username}}
                        <i class="uil uil-user"></i>
                    </div>
                    <div class="input-field">
                        {{form.email}}
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        {{form.password}}
                        <i class="uil uil-lock icon"></i>
                    </div>
                    <div class="input-field">
                        {{form.phone_number}}
                        <i class="uil uil-phone"></i>
                        <!-- <i class="uil uil-eye-slash showHidePw"></i> -->
                    </div>
                    <div class="checkbox-text">
                        <!-- <div class="checkbox-content">
                            <input type="checkbox" id="sigCheck">
                            <label for="sigCheck" class="text">Remember me</label>
                        </div> -->
                        
                        <!-- <a href="#" class="text">Forgot password?</a> -->
                    </div>

                    <div class="input-field button">
                        <input type="submit" value="register">
                        <button>Submit</button>
                    </div>
                </form>

                <div class="login-signup">
                    <span class="text">Already member?
                        <a href="{% url 'user_urls:userlogin' %}" class="text login-link">Login now</a>
                    </span>
                </div>
            </div>
        </div>
    </div>

    <script src="/static/assets/js/signup.js"></script>
       <script>
        var form_fields = document.getElementsByTagName('input')
        form_fields[1].placeholder='Username';
        form_fields[2].placeholder='email';
        form_fields[3].placeholder='password';
        form_fields[4].placeholder='Phone number';
        
        </script>

</body>
</html>

todolist/templates/userportal/update_task.html
{% extends 'userportal/base1.html' %}
{% block container %}
<div class = 'card'>
    <div class='card-header'>
        <h5 class = "class-title">Update Task</h5>
    </div>
    <div class='card-body'>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">update</button>
        </form>
    </div>
</div>
{% endblock %}

todolist/templates/userportal/view_task.html
{% extends 'userportal/base2.html' %}
{% block container %}
<table class='table'>
    <tr>
        <thead class = 'thead-light'>
            <tr>
                <th scope='col'>ID</th>
                <th scope='col'>Task_Name</th>
                <th scope='col'>Description</th>
                <th scope='col'>Priority</th>
                <th scope='col'>Date</th>

                <th scope='col'>Status</th>
                <th scope='col'>Action</th>

            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            <tr>
                <td><a href="{% url 'user_urls:detail_task' task.pk %}">{{task.id}}</a></td>
                <td>{{task.task_name}}</td>
                <td>{{task.task_description}}</td>
                <td>{{task.priority}}</td>
                <td>{{task.Date}}</td>
                <td>
                    {% if task.status == 'C'%}
                    ✅
                    {%else%}
                    🕒
                    {%endif%}
                </td>

                


                <td>
                    <!-- <a class="btn btn-danger" href = "{% url 'user_urls:delete_task' task.pk %}">Delete</a> -->
                    <a  href = "{% url 'user_urls:delete_task' task.pk %}" title="Delete">🗑️</a>
                    <a  href = "{% url 'user_urls:update_task' task.pk %}" title="Update_task">✏️</a>
                    {% if task.status == 'P' %}
                    <a  href ="/user/change-status/{{task.id}}/C" title="Mark-Completed">✅</a>
                    {% else %}
                    <a  href ="/user/change-status/{{task.id}}/P" title="Mark-Pending">🕘</a>
                    {% endif %}
                    

                </td>
            </tr>
            {% endfor %}
        </tbody>
</table>
{% endblock %}